
#Discord RichPresence Config File
[Rich-Presence]
	#First line of Rich Presence
	Client-Name = "violet.kitsuneis.life"
	#Placeholders:
	#%ip%  Server IP
	Server-Text = "Jogando no servidor"
	#No placeholders supported, Text that shows when you are in the main menu
	Main-Menu = "No menu principal"
	#Placeholders:
	#%coords% (X:??? Y:??? Z:???)
	#%world% World name
	Singleplayer-Text = "Jogando em %world% (%coords%)"
	#Setting this to true disables name changing through GUI
	Disable-Name-changing = false
	#Do you want to print log of this mod to ingame chat?
	LogToChat = false
	#Custom client id, see https://github.com/ErdbeerbaerLP/DiscordRichPresence/wiki/Set-up-custom-Icons-(for-Modpacks) for more info
	#Default: 511106082366554122
	client-id = "1358125281520521339"
	#Disables config GUI
	#Requires config file editing to enable again
	Disable-Config-GUI = false
	#Do you want to use custom Hypixel integration (show what game you are playing and such)?
	Hypixel-Integration = true
	#Do you want to use custom Hivemc integration (show what game you are playing)?
	Hivemc-Integration = true
	#Do you want servers to send you a customized rich presence text?
	#Also toggles hardcoded custom icons and text of not fully integrated servers like mineplex
	Custom-Messages-From-Server = true

