
[General]
	"Enable inventory view in shops" = true
	"Enable shipping daily ticker" = true
	"Enable sell value in tooltips" = false

[HUD]
	"Enable clock HUD" = true
	"Enable gold HUD" = true
	"Enable gold icon in HUD" = true
	#Range: > -2147483648
	"Gold HUD X Offset" = 0
	#Range: > -2147483648
	"Gold HUD Y Offset" = 0
	#Allowed Values: LEFT, RIGHT
	"Gold HUD render side" = "LEFT"

